name: Check for Non-ASCII Characters

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-non-ascii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history so we can compare appropriately

    - name: Find non-ASCII characters
      id: find_non_ascii
      run: |
        files_with_non_ascii=""
        changed_files=""
        # Use the correct name for your default branch
        default_branch=nzp-unicode
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        monitored_dirs="./ct ./install ./misc"

        echo "Default branch: $default_branch"
        echo "Current branch: $current_branch"
        echo "Monitored directories: $monitored_dirs"

        echo "Comparing branches: origin/$default_branch...HEAD"

        # List all changed files in the PR
        changed_files=$(git diff --name-only origin/$default_branch...HEAD)
        echo "Changed files in the PR:\n$changed_files"

        for dir in $monitored_dirs; do
          echo "Checking directory: $dir"
          for file in $(git diff --name-only origin/$default_branch...HEAD -- "$dir/*"); do
            echo "Checking file: $file"
            if file --mime --brief "$file" | grep -q 'text/'; then
              echo "File is a text file: $file"
              if grep --quiet --perl-regexp '[^\x00-\x7F]' "$file"; then
                echo "File contains non-ASCII characters: $file"
                files_with_non_ascii="$files_with_non_ascii $file"
              else
                echo "File does not contain non-ASCII characters: $file"
              fi
            else
              echo "File is not a text file: $file"
            fi
          done
        done

        echo "Files with non-ASCII characters: $files_with_non_ascii"
        echo "files=$files_with_non_ascii" >> $GITHUB_ENV

    - name: Create comment
      if: env.files != ''
      uses: actions/github-script@v7
      with:
        script: |
          const files = process.env.files.split(' ').filter(f => f).map(f => {
            return JSON.stringify(f);
          }).join('\n');
          
          if (files) {
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: `⚠️ Warning: The following files contain non-ASCII characters:\n${files.replace(/"/g, '')}`
            });
          }
