name: Check for Non-ASCII Characters

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-non-ascii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history so we can compare appropriately

    - name: Find non-ASCII characters
      id: find_non_ascii
      run: |
        files_with_non_ascii=""
        # Use the correct name for your default branch
        default_branch=nzp-unicode-test
        monitored_dirs="./ct ./install ./misc"
        
        for dir in $monitored_dirs; do
          for file in $(git diff --name-only origin/$default_branch...HEAD -- "$dir/*"); do
            if file --mime --brief "$file" | grep -q 'text/'; then
              if grep --quiet --perl-regexp '[^\x00-\x7F]' "$file"; then
                files_with_non_ascii="$files_with_non_ascii $file"
              fi
            fi
          done
        done
        
        echo "files=$files_with_non_ascii" >> $GITHUB_ENV

    - name: Create comment
      if: env.files != ''
      uses: actions/github-script@v5
      with:
        script: |
          const files = process.env.files.split(' ').filter(f => f).map(f => {
            return JSON.stringify(f);
          }).join('\n');
          
          if (files) {
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: `⚠️ Warning: The following files contain non-ASCII characters:\n${files.replace(/"/g, '')}`
            });
          }